networks:
  proxy:
    name: backbone_proxy
    external: true
  monitoring:
    name: backbone_monitoring
    external: true

services:
  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    restart: always
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    labels:
      - traefik.http.routers.prometheus.middlewares=${MIDDLEWARES:-}
      - traefik.enable=true
      - traefik.docker.network=backbone_proxy
      - traefik.http.routers.prometheus.ruleSyntax=v3
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.routers.prometheus.tls.certresolver=${CERTRESOLVER:-}
      - traefik.http.routers.prometheus.entryPoints=https
      - traefik.http.routers.prometheus.rule=Host("prom.${HOST_FQDN}")
      - traefik.http.routers.prometheus.service=prometheus-service
      - traefik.http.services.prometheus-service.loadbalancer.server.port=9090
      - prometheus.scrape=true
      - prometheus.port=9090
    environment:
      TZ: Europe/Berlin
    networks:
      - monitoring 
      - proxy

  alertmanager:
    image: prom/alertmanager:v0.28.1
    container_name: alertmanager
    restart: always
    volumes:
      - ./alertmanager/config:/etc/alertmanager
      - ./alertmanager/data:/data
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    labels:
      - traefik.http.routers.alertmanager.middlewares=${MIDDLEWARES:-}
      - traefik.enable=true
      - traefik.docker.network=backbone_proxy
      - traefik.http.routers.alertmanager.ruleSyntax=v3
      - traefik.http.routers.alertmanager.tls=true
      - traefik.http.routers.alertmanager.tls.certresolver=${CERTRESOLVER:-}
      - traefik.http.routers.alertmanager.entryPoints=https
      - traefik.http.routers.alertmanager.rule=Host("alert.${HOST_FQDN}")
      - traefik.http.routers.alertmanager.service=alertmanager-service
      - traefik.http.services.alertmanager-service.loadbalancer.server.port=9093
    environment:
      TZ: Europe/Berlin
    networks:
      - monitoring
      - proxy

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.0
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    labels:
      - prometheus.scrape=true
      - prometheus.port=9100
      - prometheus.job=infrastructure
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - monitoring
