global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'monitoring' 
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'infrastructure'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['node_exporter:9100', 'cadvisor:8080', 'reverse_proxy:8080/metrics']

  - job_name: 'database'
    scrape_interval: 5s

    static_configs:
      - targets: ['mariadb-mon:9104']

  - job_name: 'nextcloud'
    static_configs:
      - targets: ['nextcloud-mon:9205']

