global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'monitoring' 
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # Only keep containers that have a `prometheus.scrape` label set to true.
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        regex: "true"
        action: keep

      # Only keep those that are in network named backbone_monitoring.
      - source_labels: [__meta_docker_network_name]
        regex: backbone_monitoring
        action: keep

      # allow override of http scheme with `promehteus.scheme`
      - action: replace
        regex: (https?)
        source_labels: [__meta_docker_container_label_prometheus_scheme]
        target_label: __scheme__

      # allow override of default /metrics path with `prometheus.path`
      - action: replace
        regex: (.+)
        source_labels: [__meta_docker_container_label_prometheus_path]
        target_label: __metrics_path__

      # allow override of default port with `prometheus.port`
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels: [__address__, __meta_docker_container_label_prometheus_port]
        target_label: __address__

      # Add all labels
      - {action: labelmap, regex: __meta_docker_container_label_(.+)}
