global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'

scrape_config_files:
  - "scraper-*.yml"

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        match_first_network: false
    relabel_configs:
      # Only keep containers that have a `prometheus.scrape` label set to true.
      - source_labels: [__meta_docker_container_label_prometheus_scrape]
        regex: "true"
        action: keep

      # Only keep those that are in network named backbone_monitoring.
      - source_labels: [__meta_docker_network_name]
        regex: (backbone_monitoring|host)
        action: keep

      # override scrap target expecialy for node exporter
      #- action: replace
      #  regex: (?:[^:]+)(?:(?::)(\d+))?(?::\d+)?;([^:]+)
      #  replacement: $2:$1
      #  source_labels: [__address__,__meta_docker_container_label_prometheus_address]
      #  target_label: __address__

      # allow override of http scheme with `promehteus.scheme`
      - action: replace
        regex: (https?)
        source_labels: [__meta_docker_container_label_prometheus_scheme]
        target_label: __scheme__

      # allow override of default /metrics path with `prometheus.path`
      - action: replace
        regex: (.+)
        source_labels: [__meta_docker_container_label_prometheus_path]
        target_label: __metrics_path__

      # allow override of default port with `prometheus.port`
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels: [__address__, __meta_docker_container_label_prometheus_port]
        target_label: __address__

      # allow override of job with 'prometheus.job'
      - action: replace
        regex: (.+)
        source_labels: [__meta_docker_container_label_prometheus_job]
        target_label: job

      # replace hoste name with traefik configuration
      - action: replace
        regex: (.+)
        source_labels: [__meta_docker_container_label_prometheus_host]
        target_label: instance

      # override scrap target expecialy for node exporter
      - action: replace
        regex: (?:[^:]+)(?:(?::)(\d+))?(?::\d+)?;([^:]+)
        replacement: $2:$1
        source_labels: [__address__,__meta_docker_container_label_prometheus_address]
        target_label: __address__

      # Add all labels
      - {action: labelmap, regex: __meta_docker_container_label_(.+)}
